export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as LeaderBoard } from './LeaderBoard'
export { default as Login } from './Login'
export { default as NewQuestion } from './NewQuestion'
export { default as Poll } from './Poll'
export { default as Result } from './Result'